webtalk_init -webtalk_dir /home/centos/git/dandelion-aws/hdk/cl/developer_designs/cl_dandelion_acc/verif/sim/vivado/test_dandelion_hwsw_cosim_c/xsim.dir/tb/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 22 20:56:11 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.op (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4f5ef465-e1c9-4f4b-ad16-5241afbb6170" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1db61347-b6f5-403a-9e10-f59d6c96f1ac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.8.2003 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2999.998 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "32.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "41152 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "34.68_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "187972_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4043039597 -regid "" -xml /home/centos/git/dandelion-aws/hdk/cl/developer_designs/cl_dandelion_acc/verif/sim/vivado/test_dandelion_hwsw_cosim_c/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.xml -html /home/centos/git/dandelion-aws/hdk/cl/developer_designs/cl_dandelion_acc/verif/sim/vivado/test_dandelion_hwsw_cosim_c/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.html -wdm /home/centos/git/dandelion-aws/hdk/cl/developer_designs/cl_dandelion_acc/verif/sim/vivado/test_dandelion_hwsw_cosim_c/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
