webtalk_init -webtalk_dir /home/centos/git/dandelion-aws/hdk/cl/developer_designs/cl_dandelion_acc/verif/sim/vivado/test_dram_dma_hwsw_cosim_c/xsim.dir/tb/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar  3 23:18:44 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.op (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4f5ef465-e1c9-4f4b-ad16-5241afbb6170" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3eb51e13-b5d5-44c2-8213-2161f958b51e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.7.1908 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2702.612 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "257.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40142 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "14.43_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "183900_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2174492971 -regid "" -xml /home/centos/git/dandelion-aws/hdk/cl/developer_designs/cl_dandelion_acc/verif/sim/vivado/test_dram_dma_hwsw_cosim_c/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.xml -html /home/centos/git/dandelion-aws/hdk/cl/developer_designs/cl_dandelion_acc/verif/sim/vivado/test_dram_dma_hwsw_cosim_c/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.html -wdm /home/centos/git/dandelion-aws/hdk/cl/developer_designs/cl_dandelion_acc/verif/sim/vivado/test_dram_dma_hwsw_cosim_c/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
